{% set name = "pytcube" %}
{% set version = "0.0.3a3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c21e62cd7c132a903719feecbb24131003836b26818394c32efed7ea89a839a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - dask >=2024.6
    - fast_vindex >=0.0.2
    - numpy >=1.26
    - pandas >=2.2
    - xarray >=2024.10.0
    
test:
  imports:
    - pytcube
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check


about:
  home: https://gitlab.ifremer.fr/odatis-public/pytcube
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: "PytCube extracts small subsets around observation points within large multidimensional datasets."

extra:
  recipe-maintainers:
    - GwenaelCaer
