{% set name = "pytcube" %}
{% set version = "0.0.3a2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/odatis-public/{{ name }}/-/archive/{{ version }}/{{ name }}-{{version}}.tar.gz
  sha256: 96ca9708511b1dcc96b32e0cf04f590e5cc69a671747572410d2a0fca0d1d11b 

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - dask >=2024.6
    - fast-vindex >=0.0.2
    - pandas >=2.2
    - numpy >=1.26
    - xarray >=2024.10.0
    
test:
  imports:
    - pytcube
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check


about:
  home: https://gitlab.ifremer.fr/odatis-public/pytcube
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: "PytCube extracts small subsets around observation points within large multidimensional datasets."

extra:
  recipe-maintainers:
    - GwenaelCaer
