{% set name = "pytcube" %}
{% set version = "0.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/odatis-public/{{ name }}/-/archive/main/{{ name }}-main.tar.gz
  sha256: a2369baef73086a39168c6cf7ca840d3e841b06dc4f43bca5ffab1216bdf610f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - dask >=2024.10.0
    - dask-jobqueue >=0.9.0
    - numpy >=2.1.3
    - xarray >=2024.10.0
    - zarr >=2.18.3
    - pandas >=2.2.3
    - matplotlib-base >=3.9.2

test:
  imports:
    - pytcube
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check


about:
  home: https://gitlab.ifremer.fr/odatis-public/pytcube
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: "PytCube extracts small cubes around observation points within a large spatio-temporal datacube."

extra:
  recipe-maintainers:
    - GwenaelCaer
